version: '3'

services:
  springcat_db:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=springcat
      - POSTGRES_USER=springcat
    ports:
      - '5432:5432'
    volumes:
      - springcat_db_data:/var/lib/postgresql/data
    networks:
      - springcat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springcat"]
      interval: 10s
      timeout: 5s
      retries: 5

  springcat_web:
    build: .
    working_dir: /code/
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      springcat_db:
        condition: service_healthy
    networks:
      - springcat

volumes:
  springcat_db_data:

networks:
  springcat:
    driver: bridge