# Generated by Django 3.1.4 on 2021-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
